// flow-typed signature: 519cd50b409b5184bf2c49d1573d183c
// flow-typed version: <<STUB>>/retry_v^0.10.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'retry/example/dns' {
  declare module.exports: any;
}

declare module 'retry/example/stop' {
  declare module.exports: any;
}

declare module 'retry/lib/retry_operation' {
  declare module.exports: any;
}

declare module 'retry/lib/retry' {
  declare module.exports: any;
}

declare module 'retry/test/common' {
  declare module.exports: any;
}

declare module 'retry/test/integration/test-forever' {
  declare module.exports: any;
}

declare module 'retry/test/integration/test-retry-operation' {
  declare module.exports: any;
}

declare module 'retry/test/integration/test-retry-wrap' {
  declare module.exports: any;
}

declare module 'retry/test/integration/test-timeouts' {
  declare module.exports: any;
}

declare module 'retry/test/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'retry/example/dns.js' {
  declare module.exports: $Exports<'retry/example/dns'>;
}
declare module 'retry/example/stop.js' {
  declare module.exports: $Exports<'retry/example/stop'>;
}
declare module 'retry/index' {
  declare module.exports: $Exports<'retry'>;
}
declare module 'retry/index.js' {
  declare module.exports: $Exports<'retry'>;
}
declare module 'retry/lib/retry_operation.js' {
  declare module.exports: $Exports<'retry/lib/retry_operation'>;
}
declare module 'retry/lib/retry.js' {
  declare module.exports: $Exports<'retry/lib/retry'>;
}
declare module 'retry/test/common.js' {
  declare module.exports: $Exports<'retry/test/common'>;
}
declare module 'retry/test/integration/test-forever.js' {
  declare module.exports: $Exports<'retry/test/integration/test-forever'>;
}
declare module 'retry/test/integration/test-retry-operation.js' {
  declare module.exports: $Exports<'retry/test/integration/test-retry-operation'>;
}
declare module 'retry/test/integration/test-retry-wrap.js' {
  declare module.exports: $Exports<'retry/test/integration/test-retry-wrap'>;
}
declare module 'retry/test/integration/test-timeouts.js' {
  declare module.exports: $Exports<'retry/test/integration/test-timeouts'>;
}
declare module 'retry/test/runner.js' {
  declare module.exports: $Exports<'retry/test/runner'>;
}
