// flow-typed signature: d7c681ff870d47fb4bfa6e3b0b3062d9
// flow-typed version: <<STUB>>/slack-node_v^0.1.8/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slack-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slack-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slack-node/example/api.postMessage' {
  declare module.exports: any;
}

declare module 'slack-node/example/emoji' {
  declare module.exports: any;
}

declare module 'slack-node/example/webhook' {
  declare module.exports: any;
}

declare module 'slack-node/lib/index' {
  declare module.exports: any;
}

declare module 'slack-node/lib/lib/slack.seed' {
  declare module.exports: any;
}

declare module 'slack-node/lib/test/main.spec.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slack-node/example/api.postMessage.js' {
  declare module.exports: $Exports<'slack-node/example/api.postMessage'>;
}
declare module 'slack-node/example/emoji.js' {
  declare module.exports: $Exports<'slack-node/example/emoji'>;
}
declare module 'slack-node/example/webhook.js' {
  declare module.exports: $Exports<'slack-node/example/webhook'>;
}
declare module 'slack-node/lib/index.js' {
  declare module.exports: $Exports<'slack-node/lib/index'>;
}
declare module 'slack-node/lib/lib/slack.seed.js' {
  declare module.exports: $Exports<'slack-node/lib/lib/slack.seed'>;
}
declare module 'slack-node/lib/test/main.spec.test.js' {
  declare module.exports: $Exports<'slack-node/lib/test/main.spec.test'>;
}
