// flow-typed signature: ede94d77c27f5b8610c8eb10cbd057ac
// flow-typed version: <<STUB>>/ssh2-streams_v~0.1.15/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ssh2-streams'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ssh2-streams' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ssh2-streams/lib/constants' {
  declare module.exports: any;
}

declare module 'ssh2-streams/lib/jsbn' {
  declare module.exports: any;
}

declare module 'ssh2-streams/lib/keyParser' {
  declare module.exports: any;
}

declare module 'ssh2-streams/lib/sftp' {
  declare module.exports: any;
}

declare module 'ssh2-streams/lib/ssh' {
  declare module.exports: any;
}

declare module 'ssh2-streams/lib/utils' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-durability-ssh' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-kexdh' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-keyparser' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-packet60' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-sftp' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-ssh' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test-utils' {
  declare module.exports: any;
}

declare module 'ssh2-streams/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ssh2-streams/index' {
  declare module.exports: $Exports<'ssh2-streams'>;
}
declare module 'ssh2-streams/index.js' {
  declare module.exports: $Exports<'ssh2-streams'>;
}
declare module 'ssh2-streams/lib/constants.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/constants'>;
}
declare module 'ssh2-streams/lib/jsbn.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/jsbn'>;
}
declare module 'ssh2-streams/lib/keyParser.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/keyParser'>;
}
declare module 'ssh2-streams/lib/sftp.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/sftp'>;
}
declare module 'ssh2-streams/lib/ssh.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/ssh'>;
}
declare module 'ssh2-streams/lib/utils.js' {
  declare module.exports: $Exports<'ssh2-streams/lib/utils'>;
}
declare module 'ssh2-streams/test/test-durability-ssh.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-durability-ssh'>;
}
declare module 'ssh2-streams/test/test-kexdh.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-kexdh'>;
}
declare module 'ssh2-streams/test/test-keyparser.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-keyparser'>;
}
declare module 'ssh2-streams/test/test-packet60.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-packet60'>;
}
declare module 'ssh2-streams/test/test-sftp.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-sftp'>;
}
declare module 'ssh2-streams/test/test-ssh.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-ssh'>;
}
declare module 'ssh2-streams/test/test-utils.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test-utils'>;
}
declare module 'ssh2-streams/test/test.js' {
  declare module.exports: $Exports<'ssh2-streams/test/test'>;
}
