export const CpuUsage      = 'cpuUsage'
export const SwapUsed      = 'swapUsedPercentage'
export const MemoryUsed    = 'memoryUsedPercentage'
export const AverageLoad   = 'averageLoad'
export const DiskSpaceUsed = 'percentageDiskSpaceUsed'
